Initialize Rust-backend using Axum
dotClique/gunboat-bingo pull request #2
Opened 2023-03-25 14:28 UTC by LarsSelbekk

2023-03-26 11:24 UTC, mathiazom requested changes
I think it makes sense to maintain a seperate Rust-specific .gitignore for the backend directory, in addition to the top level one.

2023-03-26 17:25 UTC, redrei commented on backend/Cargo.toml
> +axum = { version = "0.6.12", features = ["http2"] }
hvorfor 0.6.12 og ikke den nyeste releasen [0.7.2](https://github.com/tokio-rs/axum/releases/tag/axum-extra-v0.7.2)?

2023-03-26 17:42 UTC, redrei approved these changes
Okay init

2023-04-15 11:10 UTC, ulrik2204 approved these changes
LGTM

2023-04-15 11:18 UTC, mathiazom approved these changes

2023-04-15 11:20 UTC, merged